image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mongo:latest

stages:
  - build
  - package

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - TypeScript-RestAPI/node_modules/

build_code:
  stage: build
  script:
   - cd TypeScript-RestAPI
   - npm install
   - npm run build

package_code:
  image: docker:stable
  stage: package
  script:
    - cd TypeScript-RestAPI
    - docker info
    - docker build -t test .
